import pandas as pd


def read_cavatica_cli_filelist(filepath_or_buffer):
    """
    Read in a list of files generated by the cavatica CLI, specifically:
    `sb files list --project user/project`.
    :param filepath_or_buffer: a file list generated by the cavatica CLI
    :type filepath_or_buffer: string (path) or file-like object
    :return: The structured contents of the file
    :rtype: pandas.Dataframe
    """
    out = pd.read_csv(
        filepath_or_buffer,
        sep="\t",
        names=["cavatica_id", "file_name", "cavatica_location"],
    )
    return out
